version: '3'

services:
  store-service:
    build:
      context: ./store-service 
    ports:
      - "8081:8081"
  
  consumer-service:
    build:
      context: ./consumer-service
    ports:
      - "8080:8080"
